### ISSUE TITLE
`-std=c89` flag build error

### ISSUE THREAD

**Issue by LesnyRumcajs** [launchdarkly/c-server-sdk#32]
Hello, I would like to understand why was the `-std=c89` flag recently introduced in the `CMakeLists.txt`. Unfortunately it breaks builds with `clang`. E.g.
```
:587:13: error: '_Bool' is a C99 extension [-Werror,-Wc99-extensions]
            bool           variationMatch = false;
            ^
/usr/lib/clang/11.0.1/include/stdbool.h:15:14: note: expanded from macro 'bool'
```
Could you please advise on this issue? Please see a similar one: https://github.com/protocolbuffers/upb/pull/213

**Comment by hroederld** [comment]
Hello @LesnyRumcajs 

We published a new release `2.3.3` today that should remedy the issue (1) by removing stray references to `stdbool.h`. With the `c-server-sdk` we aim for a wide range of compatibility, and defining a custom boolean type is fairly common for C libraries.

My main concern here is why this was not caught by CI. We build for Linux / Windows / MacOS, and test builds with clang, msvc, and gcc. Could you share a little more about your environment such as version of clang, operating system, and operating system version?

1. https://github.com/launchdarkly/c-server-sdk/releases/tag/2.3.3

**Comment by LesnyRumcajs** [comment]
Hello @hroederld .

Actually it failed in two systems - my local machine with `MacOS Big Sur 11.4`, compiling under `AppleClang 12.0.5.12050022` and build container with `Debian GNU/Linux 10 (buster)` and `Debian clang version 11.0.1-2`.

Unfortunately it's still failing in 2.3.3, there's yet another `stdbool.h` include in `third-party/include/timestamp.h`.

**Comment by hroederld** [comment]
@LesnyRumcajs Ah I see the issue. Both during local development and in CI we are using an older clang version. When I tryout clang-11 I can replicate the build failure.

**Comment by hroederld** [comment]
@LesnyRumcajs 

The new release `2.3.4` has a fix and we also added a more recent version of clang to CI which should hopefully catch such things in the future.

**Comment by LesnyRumcajs** [comment]
@hroederld Thanks a lot, works fine now!
